// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace Remnant
{
public static class GPGSIds
{
        public const string event_galaxy_07_level_02_stars = "CgkI6Ya_9ZgaEAIQgAE"; // <GPGSID>
        public const string event_galaxy_06_level_02_attempts = "CgkI6Ya_9ZgaEAIQIA"; // <GPGSID>
        public const string event_galaxy_01_level_03_attempts = "CgkI6Ya_9ZgaEAIQCA"; // <GPGSID>
        public const string event_galaxy_06_level_05_attempts = "CgkI6Ya_9ZgaEAIQIw"; // <GPGSID>
        public const string event_galaxy_08_level_04_wins = "CgkI6Ya_9ZgaEAIQVA"; // <GPGSID>
        public const string event_ship_02_purchased = "CgkI6Ya_9ZgaEAIQjQE"; // <GPGSID>
        public const string event_galaxy_04_level_02_stars = "CgkI6Ya_9ZgaEAIQcQ"; // <GPGSID>
        public const string event_galaxy_01_level_02_attempts = "CgkI6Ya_9ZgaEAIQBw"; // <GPGSID>
        public const string achievement_perfectionist = "CgkI6Ya_9ZgaEAIQXg"; // <GPGSID>
        public const string event_galaxy_04_level_04_stars = "CgkI6Ya_9ZgaEAIQcw"; // <GPGSID>
        public const string event_galaxy_05_level_02_stars = "CgkI6Ya_9ZgaEAIQdg"; // <GPGSID>
        public const string event_ship_06_purchased = "CgkI6Ya_9ZgaEAIQkQE"; // <GPGSID>
        public const string event_galaxy_05_level_01_attempts = "CgkI6Ya_9ZgaEAIQGg"; // <GPGSID>
        public const string event_galaxy_03_level_03_wins = "CgkI6Ya_9ZgaEAIQOg"; // <GPGSID>
        public const string event_galaxy_05_level_04_attempts = "CgkI6Ya_9ZgaEAIQHQ"; // <GPGSID>
        public const string event_galaxy_01_level_01_wins = "CgkI6Ya_9ZgaEAIQLg"; // <GPGSID>
        public const string event_galaxy_04_level_01_attempts = "CgkI6Ya_9ZgaEAIQFQ"; // <GPGSID>
        public const string event_galaxy_06_level_03_wins = "CgkI6Ya_9ZgaEAIQSQ"; // <GPGSID>
        public const string event_galaxy_04_level_01_wins = "CgkI6Ya_9ZgaEAIQPQ"; // <GPGSID>
        public const string achievement_experienced_pioneer = "CgkI6Ya_9ZgaEAIQWQ"; // <GPGSID>
        public const string event_galaxy_01_level_02_stars = "CgkI6Ya_9ZgaEAIQYg"; // <GPGSID>
        public const string event_resources_spent = "CgkI6Ya_9ZgaEAIQlQE"; // <GPGSID>
        public const string event_galaxy_05_level_02_attempts = "CgkI6Ya_9ZgaEAIQGw"; // <GPGSID>
        public const string achievement_multiplanetary_linguist = "CgkI6Ya_9ZgaEAIQWw"; // <GPGSID>
        public const string event_galaxy_02_level_04_stars = "CgkI6Ya_9ZgaEAIQaQ"; // <GPGSID>
        public const string event_galaxy_07_level_04_stars = "CgkI6Ya_9ZgaEAIQggE"; // <GPGSID>
        public const string event_galaxy_01_level_04_wins = "CgkI6Ya_9ZgaEAIQMQ"; // <GPGSID>
        public const string event_galaxy_08_level_03_stars = "CgkI6Ya_9ZgaEAIQhgE"; // <GPGSID>
        public const string event_galaxy_02_level_01_stars = "CgkI6Ya_9ZgaEAIQZg"; // <GPGSID>
        public const string event_galaxy_08_level_02_attempts = "CgkI6Ya_9ZgaEAIQKg"; // <GPGSID>
        public const string event_galaxy_03_level_03_attempts = "CgkI6Ya_9ZgaEAIQEg"; // <GPGSID>
        public const string event_galaxy_08_level_05_attempts = "CgkI6Ya_9ZgaEAIQLQ"; // <GPGSID>
        public const string event_galaxy_04_level_01_stars = "CgkI6Ya_9ZgaEAIQcA"; // <GPGSID>
        public const string event_galaxy_04_level_05_stars = "CgkI6Ya_9ZgaEAIQdA"; // <GPGSID>
        public const string event_galaxy_07_level_04_wins = "CgkI6Ya_9ZgaEAIQTw"; // <GPGSID>
        public const string event_galaxy_05_level_02_wins = "CgkI6Ya_9ZgaEAIQQw"; // <GPGSID>
        public const string event_galaxy_08_level_03_wins = "CgkI6Ya_9ZgaEAIQUw"; // <GPGSID>
        public const string event_galaxy_06_level_01_stars = "CgkI6Ya_9ZgaEAIQeg"; // <GPGSID>
        public const string event_galaxy_04_level_03_stars = "CgkI6Ya_9ZgaEAIQcg"; // <GPGSID>
        public const string event_galaxy_08_level_05_wins = "CgkI6Ya_9ZgaEAIQVQ"; // <GPGSID>
        public const string event_galaxy_08_level_02_wins = "CgkI6Ya_9ZgaEAIQUg"; // <GPGSID>
        public const string event_ship_04_purchased = "CgkI6Ya_9ZgaEAIQjwE"; // <GPGSID>
        public const string event_galaxy_05_level_05_stars = "CgkI6Ya_9ZgaEAIQeQ"; // <GPGSID>
        public const string event_galaxy_02_level_02_attempts = "CgkI6Ya_9ZgaEAIQDA"; // <GPGSID>
        public const string event_galaxy_07_level_04_attempts = "CgkI6Ya_9ZgaEAIQJw"; // <GPGSID>
        public const string event_galaxy_02_level_05_attempts = "CgkI6Ya_9ZgaEAIQDw"; // <GPGSID>
        public const string event_galaxy_06_level_01_attempts = "CgkI6Ya_9ZgaEAIQHw"; // <GPGSID>
        public const string achievement_novice_adventurer = "CgkI6Ya_9ZgaEAIQVw"; // <GPGSID>
        public const string event_galaxy_06_level_04_attempts = "CgkI6Ya_9ZgaEAIQIg"; // <GPGSID>
        public const string event_galaxy_01_level_05_attempts = "CgkI6Ya_9ZgaEAIQCg"; // <GPGSID>
        public const string event_galaxy_05_level_05_wins = "CgkI6Ya_9ZgaEAIQRg"; // <GPGSID>
        public const string event_ship_01_purchased = "CgkI6Ya_9ZgaEAIQjAE"; // <GPGSID>
        public const string achievement_renown_space_grandmaster = "CgkI6Ya_9ZgaEAIQXA"; // <GPGSID>
        public const string event_galaxy_03_level_01_wins = "CgkI6Ya_9ZgaEAIQOA"; // <GPGSID>
        public const string event_galaxy_01_level_05_stars = "CgkI6Ya_9ZgaEAIQZQ"; // <GPGSID>
        public const string event_galaxy_02_level_03_wins = "CgkI6Ya_9ZgaEAIQNQ"; // <GPGSID>
        public const string event_galaxy_06_level_05_stars = "CgkI6Ya_9ZgaEAIQfg"; // <GPGSID>
        public const string event_galaxy_07_level_05_wins = "CgkI6Ya_9ZgaEAIQUA"; // <GPGSID>
        public const string event_galaxy_02_level_05_wins = "CgkI6Ya_9ZgaEAIQNw"; // <GPGSID>
        public const string event_galaxy_06_level_01_wins = "CgkI6Ya_9ZgaEAIQRw"; // <GPGSID>
        public const string achievement_space_craft_savant = "CgkI6Ya_9ZgaEAIQXQ"; // <GPGSID>
        public const string event_galaxy_02_level_05_stars = "CgkI6Ya_9ZgaEAIQag"; // <GPGSID>
        public const string achievement_lost_alone__scared = "CgkI6Ya_9ZgaEAIQAQ"; // <GPGSID>
        public const string event_galaxy_07_level_01_stars = "CgkI6Ya_9ZgaEAIQfw"; // <GPGSID>
        public const string event_galaxy_05_level_03_attempts = "CgkI6Ya_9ZgaEAIQHA"; // <GPGSID>
        public const string event_galaxy_07_level_02_wins = "CgkI6Ya_9ZgaEAIQTQ"; // <GPGSID>
        public const string event_resources_earned = "CgkI6Ya_9ZgaEAIQYA"; // <GPGSID>
        public const string event_galaxy_04_level_03_attempts = "CgkI6Ya_9ZgaEAIQFw"; // <GPGSID>
        public const string event_galaxy_03_level_04_wins = "CgkI6Ya_9ZgaEAIQOw"; // <GPGSID>
        public const string event_galaxy_01_level_02_wins = "CgkI6Ya_9ZgaEAIQLw"; // <GPGSID>
        public const string event_galaxy_06_level_02_stars = "CgkI6Ya_9ZgaEAIQew"; // <GPGSID>
        public const string event_galaxy_03_level_04_stars = "CgkI6Ya_9ZgaEAIQbg"; // <GPGSID>
        public const string event_galaxy_07_level_03_stars = "CgkI6Ya_9ZgaEAIQgQE"; // <GPGSID>
        public const string event_galaxy_06_level_04_wins = "CgkI6Ya_9ZgaEAIQSg"; // <GPGSID>
        public const string event_ship_08_purchased = "CgkI6Ya_9ZgaEAIQkwE"; // <GPGSID>
        public const string event_galaxy_04_level_02_wins = "CgkI6Ya_9ZgaEAIQPg"; // <GPGSID>
        public const string event_galaxy_03_level_01_stars = "CgkI6Ya_9ZgaEAIQaw"; // <GPGSID>
        public const string event_ship_07_purchased = "CgkI6Ya_9ZgaEAIQkgE"; // <GPGSID>
        public const string event_galaxy_08_level_01_stars = "CgkI6Ya_9ZgaEAIQhAE"; // <GPGSID>
        public const string event_stars_earned = "CgkI6Ya_9ZgaEAIQBA"; // <GPGSID>
        public const string event_galaxy_04_level_05_attempts = "CgkI6Ya_9ZgaEAIQGQ"; // <GPGSID>
        public const string event_galaxy_08_level_01_attempts = "CgkI6Ya_9ZgaEAIQKQ"; // <GPGSID>
        public const string event_galaxy_03_level_02_attempts = "CgkI6Ya_9ZgaEAIQEQ"; // <GPGSID>
        public const string event_galaxy_08_level_04_attempts = "CgkI6Ya_9ZgaEAIQLA"; // <GPGSID>
        public const string event_galaxy_01_level_05_wins = "CgkI6Ya_9ZgaEAIQMg"; // <GPGSID>
        public const string event_galaxy_07_level_01_attempts = "CgkI6Ya_9ZgaEAIQJA"; // <GPGSID>
        public const string event_galaxy_05_level_03_stars = "CgkI6Ya_9ZgaEAIQdw"; // <GPGSID>
        public const string event_galaxy_04_level_05_wins = "CgkI6Ya_9ZgaEAIQQQ"; // <GPGSID>
        public const string event_ship_05_purchased = "CgkI6Ya_9ZgaEAIQkAE"; // <GPGSID>
        public const string event_galaxy_02_level_01_wins = "CgkI6Ya_9ZgaEAIQMw"; // <GPGSID>
        public const string event_galaxy_05_level_03_wins = "CgkI6Ya_9ZgaEAIQRA"; // <GPGSID>
        public const string leaderboard_resources_earned = "CgkI6Ya_9ZgaEAIQXw"; // <GPGSID>
        public const string event_galaxy_06_level_02_wins = "CgkI6Ya_9ZgaEAIQSA"; // <GPGSID>
        public const string event_galaxy_07_level_05_stars = "CgkI6Ya_9ZgaEAIQgwE"; // <GPGSID>
        public const string event_galaxy_02_level_01_attempts = "CgkI6Ya_9ZgaEAIQCw"; // <GPGSID>
        public const string event_galaxy_07_level_03_attempts = "CgkI6Ya_9ZgaEAIQJg"; // <GPGSID>
        public const string event_galaxy_02_level_04_attempts = "CgkI6Ya_9ZgaEAIQDg"; // <GPGSID>
        public const string event_galaxy_01_level_03_stars = "CgkI6Ya_9ZgaEAIQYw"; // <GPGSID>
        public const string event_galaxy_01_level_01_attempts = "CgkI6Ya_9ZgaEAIQBg"; // <GPGSID>
        public const string event_galaxy_06_level_03_attempts = "CgkI6Ya_9ZgaEAIQIQ"; // <GPGSID>
        public const string event_galaxy_01_level_04_attempts = "CgkI6Ya_9ZgaEAIQCQ"; // <GPGSID>
        public const string event_galaxy_02_level_03_attempts = "CgkI6Ya_9ZgaEAIQDQ"; // <GPGSID>
        public const string event_galaxy_02_level_04_wins = "CgkI6Ya_9ZgaEAIQNg"; // <GPGSID>
        public const string event_galaxy_03_level_05_stars = "CgkI6Ya_9ZgaEAIQbw"; // <GPGSID>
        public const string event_galaxy_03_level_02_wins = "CgkI6Ya_9ZgaEAIQOQ"; // <GPGSID>
        public const string event_galaxy_03_level_02_stars = "CgkI6Ya_9ZgaEAIQbA"; // <GPGSID>
        public const string leaderboard_stars_earned = "CgkI6Ya_9ZgaEAIQAg"; // <GPGSID>
        public const string event_galaxy_08_level_04_stars = "CgkI6Ya_9ZgaEAIQhwE"; // <GPGSID>
        public const string achievement_trained_navigator = "CgkI6Ya_9ZgaEAIQWA"; // <GPGSID>
        public const string event_galaxy_05_level_05_attempts = "CgkI6Ya_9ZgaEAIQHg"; // <GPGSID>
        public const string event_galaxy_04_level_02_attempts = "CgkI6Ya_9ZgaEAIQFg"; // <GPGSID>
        public const string event_galaxy_07_level_01_wins = "CgkI6Ya_9ZgaEAIQTA"; // <GPGSID>
        public const string event_galaxy_06_level_04_stars = "CgkI6Ya_9ZgaEAIQfQ"; // <GPGSID>
        public const string event_ship_03_purchased = "CgkI6Ya_9ZgaEAIQjgE"; // <GPGSID>
        public const string event_galaxy_05_level_04_stars = "CgkI6Ya_9ZgaEAIQeA"; // <GPGSID>
        public const string event_galaxy_01_level_04_stars = "CgkI6Ya_9ZgaEAIQZA"; // <GPGSID>
        public const string event_galaxy_03_level_05_wins = "CgkI6Ya_9ZgaEAIQPA"; // <GPGSID>
        public const string event_galaxy_01_level_03_wins = "CgkI6Ya_9ZgaEAIQMA"; // <GPGSID>
        public const string event_galaxy_05_level_01_stars = "CgkI6Ya_9ZgaEAIQdQ"; // <GPGSID>
        public const string event_galaxy_06_level_05_wins = "CgkI6Ya_9ZgaEAIQSw"; // <GPGSID>
        public const string event_galaxy_04_level_03_wins = "CgkI6Ya_9ZgaEAIQPw"; // <GPGSID>
        public const string event_galaxy_04_level_04_attempts = "CgkI6Ya_9ZgaEAIQGA"; // <GPGSID>
        public const string achievement_curious_explorer = "CgkI6Ya_9ZgaEAIQVg"; // <GPGSID>
        public const string event_galaxy_06_level_03_stars = "CgkI6Ya_9ZgaEAIQfA"; // <GPGSID>
        public const string event_galaxy_03_level_01_attempts = "CgkI6Ya_9ZgaEAIQEA"; // <GPGSID>
        public const string event_galaxy_08_level_03_attempts = "CgkI6Ya_9ZgaEAIQKw"; // <GPGSID>
        public const string event_galaxy_03_level_04_attempts = "CgkI6Ya_9ZgaEAIQEw"; // <GPGSID>
        public const string event_galaxy_05_level_01_wins = "CgkI6Ya_9ZgaEAIQQg"; // <GPGSID>
        public const string event_galaxy_03_level_03_stars = "CgkI6Ya_9ZgaEAIQbQ"; // <GPGSID>
        public const string event_galaxy_02_level_02_stars = "CgkI6Ya_9ZgaEAIQZw"; // <GPGSID>
        public const string event_galaxy_03_level_05_attempts = "CgkI6Ya_9ZgaEAIQFA"; // <GPGSID>
        public const string event_galaxy_01_level_01_stars = "CgkI6Ya_9ZgaEAIQYQ"; // <GPGSID>
        public const string event_galaxy_08_level_01_wins = "CgkI6Ya_9ZgaEAIQUQ"; // <GPGSID>
        public const string event_ships_purchased = "CgkI6Ya_9ZgaEAIQBQ"; // <GPGSID>
        public const string event_galaxy_08_level_05_stars = "CgkI6Ya_9ZgaEAIQiAE"; // <GPGSID>
        public const string event_galaxy_02_level_03_stars = "CgkI6Ya_9ZgaEAIQaA"; // <GPGSID>
        public const string event_galaxy_04_level_04_wins = "CgkI6Ya_9ZgaEAIQQA"; // <GPGSID>
        public const string achievement_skilled_space_captain = "CgkI6Ya_9ZgaEAIQWg"; // <GPGSID>
        public const string event_galaxy_08_level_02_stars = "CgkI6Ya_9ZgaEAIQhQE"; // <GPGSID>
        public const string event_galaxy_02_level_02_wins = "CgkI6Ya_9ZgaEAIQNA"; // <GPGSID>
        public const string event_galaxy_07_level_02_attempts = "CgkI6Ya_9ZgaEAIQJQ"; // <GPGSID>
        public const string event_galaxy_05_level_04_wins = "CgkI6Ya_9ZgaEAIQRQ"; // <GPGSID>
        public const string event_galaxy_07_level_05_attempts = "CgkI6Ya_9ZgaEAIQKA"; // <GPGSID>
        public const string event_galaxy_07_level_03_wins = "CgkI6Ya_9ZgaEAIQTg"; // <GPGSID>

}
}
