using UnityEngine;
using System.Collections;

namespace Menu {

	public enum PageType
	{
		NONE,
		SPLASH,
		MENU,
		ABOUT,
		LEVELS,
		LEVELS_REGIONS,
		HOME_GALAXY,
		DAHKRI_GALAXY,
		KYDOR_GALAXY,
		ZAX_GALAXY,
		MALIX_GALAXY,
		XILYANTIPHOR_GALAXY,
		VIDON_GALAXY,
		RYKTAR_GALAXY,
		PLAY,
		LINK,
		TUTORIALS_GALAXIES,
		TUTORIALS_HOME_GALAXY,
		TUTORIALS_UFO_GALAXIES,
		OTHER,
		STORY_LIST,
		STORY_HOME,
		STORY_DAHKRI,
		STORY_KYDOR,
		STORY_ZAX,
		STORY_MALIX,
		STORY_XILYANTIPHOR,
		STORY_VIDON,
		STORY_RYKTAR,
		SETTINGS,
		CLEAR_PROGRESS,
		CLEAR_TUTORIALS,
		GALAXY_INFO,
		LEVEL_WIN,
		LEVEL_LOSE,
		TUTORIALS_HOW_TO_PLAY,
		TUTORIALS_THRUST,
		TUTORIALS_GRAVITY_WELLS,
		TUTORIALS_ANTI_GRAVITY_WELLS,
		STORY,
		SHIP_DOCK,
		SOCIAL,
		ACHIEVEMENT_PROGRESS,
		SOCIAL_LOAD,
		PAUSE,
		SHIP_STORE
	}

}
